spring:
  main:
    banner-mode: off
  application:
    name: spring-jpa
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: root
  jpa:
    generate-ddl: false
    show-sql: true
    hibernate:
      ddl-auto: validate