### Получить список всех городов
GET http://localhost:8080/api/cities

### Получить информацию по конкретному городу
GET http://localhost:8080/api/cities/2

### Инициировать ошибку при попытке создания города
POST http://localhost:8080/api/cities
Content-Type: application/json

{
  "code": "KHVKHVKHVKHVKHVKHVKHVKHVKHVKHVKHVKHVKHVKHVKHVKHVKHVKHVKHVKHVKHVKHVKHVKHVKHVKHVKHVKHVKHVKHVKHVKHVKHVKHVKHVKHVKHVKHVKHVKHV",
  "population": 15000,
  "nameTranslationKey": {
    "translationKey": "name_khabarovsk",
    "translations": {
      "ru": "Хабаровск",
      "en": "Khabarovsk"
    }
  }
}

### Добавить город
POST http://localhost:8080/api/cities
Content-Type: application/json

{
  "code": "KHV",
  "population": 15000,
  "nameTranslationKey": {
    "translationKey": "name_khabarovsk",
    "translations": {
      "ru": "Хабаровск",
      "en": "Khabarovsk"
    }
  }
}

### Удалить город
DELETE http://localhost:8080/api/cities/4